In [1]:
import torch

## Example 0

In [2]:
x = torch.randn(20)

In [3]:
w1 = torch.randn((20,100))

In [4]:
step1 = x @ w1

In [5]:
step1.shape

torch.Size([100])

In [6]:
step2 = torch.sigmoid(step1)

In [7]:
step2.shape

torch.Size([100])

## Example 1

In [8]:
x = torch.randn(20)

In [9]:
def nn1(w1,w2,x):
    layer1 = torch.sigmoid(x @ w1)
    return layer1 @ w2

In [10]:
w1 = torch.randn((20,100))

In [11]:
w2 = torch.randn((100,1))

In [12]:
nn1(w1,w2,x)

tensor([-2.4864])

## Example 2

In [13]:
def nn2(w1,w2,w3,x):
    layer1 = torch.tanh(x @ w1)
    layer2 = torch.tanh(layer1 @ w3)
    return layer1 @ w2

In [14]:
w3 = torch.randn((100,100))

In [15]:
nn2(w1,w2,w3,x)

tensor([3.5809])

## Example 3

In [19]:
y = torch.randn(20)

In [20]:
z = torch.randn(20)

In [21]:
l = [x,y,z]

In [22]:
def nn3(w1,w2,w3,l):
    h = torch.zeros((100))
    for x in l:
        e = x @ w1
        p = h @ w3
        h = torch.relu(p + e)
    return h @ w2

In [23]:
nn3(w1,w2,w3,l)

tensor([-695.5040])