In [23]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [32]:
import numpy as np

In [33]:
A = np.arange(24)

In [34]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
A.shape

(24,)

In [36]:
A = A.reshape(6,4)

In [37]:
A.shape

(6, 4)

In [38]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
A[4,3]

19

In [40]:
A[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [41]:
A = np.ones((6,4))

In [42]:
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
A.sum()

24.0

In [21]:
A.sum(axis=0)

array([6., 6., 6., 6.])

In [22]:
A.sum(axis=1)

array([4., 4., 4., 4., 4., 4.])